version: '2.3'
services:
  trivy-adapter:
    networks:
      - harbor
    container_name: trivy-adapter
    image: docker.io/aquasec/harbor-scanner-trivy:0.7.0
    restart: always
    cap_drop:
      - ALL
    cpu_quota: 50000
    dns_search: .
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./data/trivy-adapter/trivy
        target: /home/scanner/.cache/trivy
      - type: bind
        source: ./data/trivy-adapter/reports
        target: /home/scanner/.cache/reports
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "trivy-adapter"
    env_file:
      ./common/config/trivy-adapter/env